apiVersion: v1
kind: Pod
metadata:
  name: microservicio
spec:
  containers:
    - name: hola-mundo
      image: carloscabreravas/hola-mundo:5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservicio
  template:
    metadata:
      labels:
        app: microservicio
    spec:
      containers:
        - name: hola-mundo
          image: carloscabreravas/hola-mundo:5
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: microservicio-service
spec:
  type: LoadBalancer
  selector:
    app: microservicio
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000